name: kashly_app
description: Kashly — docs & infra bootstrap
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  firebase_auth: any
  firebase_app_check: any
  cloud_firestore: any
  flutter_bloc: any
  equatable: any
  bloc: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: false