// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi_lsLe0U3oNZl3AB-ixv2Kr2TLvic_WE',
    appId: '1:143620188181:web:21767ef0a75a2ce3f3461c',
    messagingSenderId: '143620188181',
    projectId: 'kashly-511bc',
    authDomain: 'kashly-511bc.firebaseapp.com',
    storageBucket: 'kashly-511bc.firebasestorage.app',
    measurementId: 'G-Q32QHL3161',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr6-OctdBd-znT_w97fViUnPhE27UAL44',
    appId: '1:143620188181:android:c6fd488e499556f0f3461c',
    messagingSenderId: '143620188181',
    projectId: 'kashly-511bc',
    storageBucket: 'kashly-511bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK31J51gaoyzUjsOUTmVi8ydHOzuc9fU0',
    appId: '1:143620188181:ios:64245f0290eaaa8af3461c',
    messagingSenderId: '143620188181',
    projectId: 'kashly-511bc',
    storageBucket: 'kashly-511bc.firebasestorage.app',
    iosBundleId: 'com.example.kashlyApp',
  );

}